//
// String File Writer code for the Fast Light Tool Kit (FLTK).
//
// Copyright 1998-2025 by Bill Spitzak and others.
//
// This library is free software. Distribution and use rights are outlined in
// the file "COPYING" which should have been included with this file.  If this
// file is missing or damaged, see the license at:
//
//     https://www.fltk.org/COPYING.php
//
// Please see the following page on how to report bugs and issues:
//
//     https://www.fltk.org/bugs.php
//

#include "io/String_Writer.h"
#include <fstream>
#include <iomanip>

#include "Fluid.h"
#include "Project.h"
#include "nodes/Window_Node.h"
#include "nodes/Function_Node.h"

using namespace fluid;
using namespace fluid::io;

/**
 Write a string to a file, replacing all non-ASCII characters with octal codes.
 \param[in] out output file
 \param[in] text write this NUL terminated utf-8 string
 \return EOF if any of the file access calls failed, 0 if OK
 */
static int write_escaped_strings(std::ofstream &out, const char *text) {
  const unsigned char *utf8_text = (const unsigned char *)text;
  for (const unsigned char *s = utf8_text; *s; ++s) {
    unsigned char c = *s;
    // escape control characters, delete, all utf-8, and the double quotes
    // note: we should have an option in the project settings to allow utf-8
    //       characters in the output text and not escape them
    if (c < 32 || c > 126 || c == '\"') {
      if (c == '\r') {
        out << "\\r";
      } else if (c == '\n') {
        out << "\\n";
      } else {
        out << "\\" << std::setfill('0') << std::setw(3) << std::oct << (int)c << std::dec;
      }
    } else {
      out << c;
    }
  }
  return out.fail() ? EOF : 0;
}

/**
 Write a file that contains all label and tooltip strings for internationalization.
 The user is responsible to set the right file name extension. The file format
 is determined by `proj_.i18n.type`.
 \param[in] filename file path and name to a file that will hold the strings
 \return 1 if the file could not be opened for writing, or the result of `fclose`.
 */
int fluid::io::write_strings(Project &proj, const std::string &filename) {
  Node *p;
  Widget_Node *w;
  int i;

  std::ofstream fp(filename, std::ios::binary);
  if (!fp.is_open()) return 1;

  switch (proj.i18n.type) {
    case fluid::I18n_Type::NONE : /* None, just put static text out */
      fp << "# generated by Fast Light User Interface Designer (fluid) version " << FL_VERSION << "\n";
      for (auto w: proj.tree.all_widgets()) {
        if (w->label()) {
          write_escaped_strings(fp, w->label());
          fp << '\n';
        }
        if (!w->tooltip().empty()) {
          write_escaped_strings(fp, w->tooltip().c_str());
          fp << '\n';
        }
      }
      break;
    case fluid::I18n_Type::GNU : /* GNU gettext, put a .po file out */
      fp << "# generated by Fast Light User Interface Designer (fluid) version " << FL_VERSION << "\n";
      for (p = proj.tree.first; p; p = p->next) {
        if (p->is_widget()) {
          w = (Widget_Node *)p;

          if (w->label()) {
            fp << "msgid \"";
            write_escaped_strings(fp, w->label());
            fp << "\"\n";

            fp << "msgstr \"";
            write_escaped_strings(fp, w->label());
            fp << "\"\n";
          }

          if (!w->tooltip().empty()) {
            fp << "msgid \"";
            write_escaped_strings(fp, w->tooltip().c_str());
            fp << "\"\n";

            fp << "msgstr \"";
            write_escaped_strings(fp, w->tooltip().c_str());
            fp << "\"\n";
          }
        }
      }
      break;
    case fluid::I18n_Type::POSIX : /* POSIX catgets, put a .msg file out */
      fp << "$ generated by Fast Light User Interface Designer (fluid) version " << FL_VERSION << "\n";
      fp << "$set " << proj.i18n.posix_set << "\n";
      fp << "$quote \"\n";

      for (i = 1, p = proj.tree.first; p; p = p->next) {
        if (p->is_widget()) {
          w = (Widget_Node *)p;

          if (w->label()) {
            fp << i ++ << " \"";
            write_escaped_strings(fp, w->label());
            fp << "\"\n";
          }

          if (!w->tooltip().empty()) {
            fp << i ++ << " \"";
            write_escaped_strings(fp, w->tooltip().c_str());
            fp << "\"\n";
          }
        }
      }
      break;
  }

  fp.close();
  return fp.fail() ? 1 : 0;
}
