//
// Fl_Help_Dialog dialog for the Fast Light Tool Kit (FLTK).
//
// Copyright 1998-2021 by Bill Spitzak and others.
//
// This library is free software. Distribution and use rights are outlined in
// the file "COPYING" which should have been included with this file.  If this
// file is missing or damaged, see the license at:
//
//     https://www.fltk.org/COPYING.php
//
// Please see the following page on how to report bugs and issues:
//
//     https://www.fltk.org/bugs.php
//
// ========================================================================
//  DO NOT EDIT FL/Fl_Help_Dialog.H and src/Fl_Help_Dialog.cxx !!!
// ========================================================================
//  Please use fluid to change src/Fl_Help_Dialog.fl interactively
//  and then use fluid to "write code" or edit and use fluid -c .
// ========================================================================
//

// generated by Fast Light User Interface Designer (fluid) version 1.0500

#include "../FL/Fl_Help_Dialog.H"
#include <FL/Fl_Shared_Image.H>
#include "flstring.h"
#include <FL/fl_ask.H>

struct Fl_Help_Dialog::Impl {
  struct PageHistory {
    std::string file;
    int line;
  };
  std::vector<PageHistory> history_;
  int index_ { -1 };
  int max_ { 0 };
  int find_pos_ { 0 };
  int x_ { 0 };
  int y_ { 0 };
  int w_ { 530 };
  int h_ { 385 };
  Fl_Fontsize textsize_ { 12 };
  std::string value_;
  std::string file_to_load_;

  Fl_Double_Window *window_ { nullptr };
  Fl_Button *back_ { nullptr };
  Fl_Button *forward_ { nullptr };
  Fl_Button *smaller_ { nullptr };
  Fl_Button *larger_ { nullptr };
  Fl_Input *find_ { nullptr };
  Fl_Help_View *view_ { nullptr };

  void ensure_window();
  void cb_back__i(Fl_Button*, void*);
  static void cb_back_(Fl_Button*, void*);
  void cb_forward__i(Fl_Button*, void*);
  static void cb_forward_(Fl_Button*, void*);
  void cb_smaller__i(Fl_Button*, void*);
  static void cb_smaller_(Fl_Button*, void*);
  void cb_larger__i(Fl_Button*, void*);
  static void cb_larger_(Fl_Button*, void*);
  void cb_find__i(Fl_Input*, void*);
  static void cb_find_(Fl_Input*, void*);
  void cb_view__i(Fl_Help_View*, void*);
  static void cb_view_(Fl_Help_View*, void*);
};

void Fl_Help_Dialog::Impl::cb_back__i(Fl_Button*, void*) {
  if (index_ > 0)
    index_ --;

  if (index_ == 0)
    back_->deactivate();

  forward_->activate();

  if (index_ >= 0 && index_ < (int)history_.size()) {
    int l = history_[index_].line;
    if (view_->filename() == nullptr || history_[index_].file != view_->filename())
      view_->load(history_[index_].file.c_str());

    view_->topline(l);
  }
}
void Fl_Help_Dialog::Impl::cb_back_(Fl_Button* o, void* v) {
  ((Fl_Help_Dialog::Impl*)(o->parent()->parent()->user_data()))->cb_back__i(o,v);
}

void Fl_Help_Dialog::Impl::cb_forward__i(Fl_Button*, void*) {
  if (index_ < max_)
    index_ ++;

  if (index_ >= max_)
    forward_->deactivate();

  back_->activate();

  if (index_ >= 0 && index_ < (int)history_.size()) {
    int l = history_[index_].line;
    if (view_->filename() == nullptr || history_[index_].file != view_->filename())
      view_->load(history_[index_].file.c_str());

    view_->topline(l);
  }
}
void Fl_Help_Dialog::Impl::cb_forward_(Fl_Button* o, void* v) {
  ((Fl_Help_Dialog::Impl*)(o->parent()->parent()->user_data()))->cb_forward__i(o,v);
}

void Fl_Help_Dialog::Impl::cb_smaller__i(Fl_Button*, void*) {
  if (view_->textsize() > 8)
    view_->textsize(view_->textsize() - 2);

  if (view_->textsize() <= 8)
    smaller_->deactivate();
  larger_->activate();
}
void Fl_Help_Dialog::Impl::cb_smaller_(Fl_Button* o, void* v) {
  ((Fl_Help_Dialog::Impl*)(o->parent()->parent()->user_data()))->cb_smaller__i(o,v);
}

void Fl_Help_Dialog::Impl::cb_larger__i(Fl_Button*, void*) {
  if (view_->textsize() < 18)
    view_->textsize(view_->textsize() + 2);

  if (view_->textsize() >= 18)
    larger_->deactivate();
  smaller_->activate();
}
void Fl_Help_Dialog::Impl::cb_larger_(Fl_Button* o, void* v) {
  ((Fl_Help_Dialog::Impl*)(o->parent()->parent()->user_data()))->cb_larger__i(o,v);
}

void Fl_Help_Dialog::Impl::cb_find__i(Fl_Input*, void*) {
  find_pos_ = view_->find(find_->value(), find_pos_);
}
void Fl_Help_Dialog::Impl::cb_find_(Fl_Input* o, void* v) {
  ((Fl_Help_Dialog::Impl*)(o->parent()->parent()->parent()->user_data()))->cb_find__i(o,v);
}

void Fl_Help_Dialog::Impl::cb_view__i(Fl_Help_View*, void*) {
  if (view_->filename())
  {
    if (view_->changed())
    {
      index_ ++;

      if (index_ >= 100)
      {
        history_.erase(history_.begin(), history_.begin() + 10);
        index_ -= 10;
      }

      max_ = index_;

      if ((int)history_.size() <= index_) {
        history_.resize(index_ + 1);
      }

      history_[index_].file = view_->filename();
      history_[index_].line = view_->topline();

      if (index_ > 0)
        back_->activate();
      else
        back_->deactivate();

      forward_->deactivate();
      window_->label(view_->title());
    }
    else // if ! view_->changed()
    {
      if (index_ >= 0 && index_ < (int)history_.size()) {
        history_[index_].file = view_->filename();
        history_[index_].line = view_->topline();
      }
    }
  } else { // if ! view_->filename()
    index_ = 0; // hitting an internal page will disable the back/fwd buffer
    history_.resize(1);
    history_[0].file.clear();
    history_[0].line = view_->topline();
    back_->deactivate();
    forward_->deactivate();
  }
}
void Fl_Help_Dialog::Impl::cb_view_(Fl_Help_View* o, void* v) {
  ((Fl_Help_Dialog::Impl*)(o->parent()->user_data()))->cb_view__i(o,v);
}

void Fl_Help_Dialog::Impl::ensure_window() {
  if (window_) return;
  fl_register_images();
  window_ = new Fl_Double_Window(w_, h_, "Help Dialog");
  window_->user_data((void*)this);
  {
    Fl_Group* o = new Fl_Group(10, 10, 511, 25);
    {
      back_ = new Fl_Button(10, 10, 25, 25, "@<-");
      back_->tooltip("Show the previous help page.");
      back_->shortcut(0xff51);
      back_->labelcolor((Fl_Color)2);
      back_->callback((Fl_Callback*)cb_back_);
    }
    {
      forward_ = new Fl_Button(45, 10, 25, 25, "@->");
      forward_->tooltip("Show the next help page.");
      forward_->shortcut(0xff53);
      forward_->labelcolor((Fl_Color)2);
      forward_->callback((Fl_Callback*)cb_forward_);
    }
    {
      smaller_ = new Fl_Button(80, 10, 25, 25, "F");
      smaller_->tooltip("Make the help text smaller.");
      smaller_->labelfont(1);
      smaller_->labelsize(10);
      smaller_->callback((Fl_Callback*)cb_smaller_);
    }
    {
      larger_ = new Fl_Button(115, 10, 25, 25, "F");
      larger_->tooltip("Make the help text larger.");
      larger_->labelfont(1);
      larger_->labelsize(16);
      larger_->callback((Fl_Callback*)cb_larger_);
    }
    {
      Fl_Group* og = new Fl_Group(350, 10, 171, 25);
      og->box(FL_DOWN_BOX);
      og->color(FL_BACKGROUND2_COLOR);
      {
        find_ = new Fl_Input(375, 12, 143, 21, "@search");
        find_->tooltip("find text in document");
        find_->box(FL_FLAT_BOX);
        find_->labelsize(13);
        find_->textfont(4);
        find_->callback((Fl_Callback*)cb_find_);
        find_->when(FL_WHEN_ENTER_KEY_ALWAYS);
      }
      og->end();
    }
    {
      Fl_Box* ob = new Fl_Box(150, 10, 190, 25);
      Fl_Group::current()->resizable(ob);
    }
    o->end();
  }
  {
    view_ = new Fl_Help_View(10, 45, 510, 330);
    view_->box(FL_DOWN_BOX);
    view_->callback((Fl_Callback*)cb_view_);
    Fl_Group::current()->resizable(view_);
  }
  window_->size_range(260, 150);
  window_->end();

  back_->deactivate();
  forward_->deactivate();
  if (textsize_ != 12) view_->textsize(textsize_);
  if (x_ != 0 || y_ != 0) window_->position(x_, y_);
  if (w_ != 530 || h_ != 385) window_->resize(x_, y_, w_, h_);
  if (!file_to_load_.empty()) {
    view_->set_changed();
    view_->load(file_to_load_.c_str());
    window_->label(view_->title());
  } else if (!value_.empty()) {
    view_->set_changed();
    view_->value(value_.c_str());
    window_->label(view_->title());
  }
}

Fl_Help_Dialog::Fl_Help_Dialog() : impl_(new Impl()) {
}

Fl_Help_Dialog::~Fl_Help_Dialog() {
  if (impl_) {
    delete impl_->window_;
    delete impl_;
  }
}

int Fl_Help_Dialog::h() const {
  return impl_->window_ ? impl_->window_->h() : impl_->h_;
}

void Fl_Help_Dialog::hide() const {
  if (impl_->window_) impl_->window_->hide();
}

int Fl_Help_Dialog::load(const char *f) const {
  impl_->ensure_window();
  impl_->view_->set_changed();
  int ret = impl_->view_->load(f);
  impl_->window_->label(impl_->view_->title());
  return ret;
}

void Fl_Help_Dialog::position(int xx, int yy) const {
  impl_->x_ = xx;
  impl_->y_ = yy;
  if (impl_->window_) impl_->window_->position(xx, yy);
}

void Fl_Help_Dialog::resize(int xx, int yy, int ww, int hh) const {
  impl_->x_ = xx;
  impl_->y_ = yy;
  impl_->w_ = ww;
  impl_->h_ = hh;
  if (impl_->window_) impl_->window_->resize(xx, yy, ww, hh);
}

void Fl_Help_Dialog::show() const {
  impl_->ensure_window();
  impl_->window_->show();
}

void Fl_Help_Dialog::show(int argc, char **argv) const {
  impl_->ensure_window();
  impl_->window_->show(argc, argv);
}

void Fl_Help_Dialog::textsize(Fl_Fontsize s) const {
  impl_->textsize_ = s;
  if (impl_->view_) {
    impl_->view_->textsize(s);
    if (s <= 8)
      impl_->smaller_->deactivate();
    else
      impl_->smaller_->activate();

    if (s >= 18)
      impl_->larger_->deactivate();
    else
      impl_->larger_->activate();
  }
}

Fl_Fontsize Fl_Help_Dialog::textsize() const {
  return impl_->view_ ? impl_->view_->textsize() : impl_->textsize_;
}

void Fl_Help_Dialog::topline(const char *n) const {
  impl_->ensure_window();
  impl_->view_->topline(n);
}

void Fl_Help_Dialog::topline(int n) const {
  impl_->ensure_window();
  impl_->view_->topline(n);
}

void Fl_Help_Dialog::value(const char *f) const {
  impl_->ensure_window();
  impl_->view_->set_changed();
  impl_->view_->value(f);
  impl_->window_->label(impl_->view_->title());
}

const char * Fl_Help_Dialog::value() const {
  return impl_->view_ ? impl_->view_->value() : impl_->value_.c_str();
}

int Fl_Help_Dialog::visible() const {
  return impl_->window_ ? impl_->window_->visible() : 0;
}

int Fl_Help_Dialog::w() const {
  return impl_->window_ ? impl_->window_->w() : impl_->w_;
}

int Fl_Help_Dialog::x() const {
  return impl_->window_ ? impl_->window_->x() : impl_->x_;
}

int Fl_Help_Dialog::y() const {
  return impl_->window_ ? impl_->window_->y() : impl_->y_;
}
